### PR TITLE
Puppet future parser and replaced logrotate dependecy

### PR DESCRIPTION
**Pull request by aquister**

### CODE REVIEW

**Comment by cristifalcas** [comment]
i was thinking to remove logrotate from the module in a future release. Whoever needs it, can set logrotate externally.

If it's ok with you, could you do it in this PR?

**Comment by cristifalcas** [comment]
Thank you for your work.

**Comment by aquister** [comment]
Are there any good reasons for removing the logrotate rule? 
I dont know if hekad.log tends to take up a log of space after a while, but I would assume logrotate is a quite crucial feature if it does.

**Comment by cristifalcas** [comment]
Heka never rotates the log file.

Ok then, I will keep it.

Thanbk you for your PR.

**Pull request merged**
